### ISSUE TITLE
Limitation

### ISSUE THREAD

**Issue by idokaplan** [YSmetana/raid_arcconf_zabbix_lld#3]
Hi,

Is there a reason that you have limited the range of logical and physical devices to only id 0-9?

Thanks!
Ido

**Comment by YuriySm** [comment]
Hi! Sorry for the delay.

There is no way to get the P. Devices quantity. So I need to check if the P. Device exist using the simple loop (ID from 0 to 9).

There is a little pause in the command response, so if you have many iteration the discovery script will might run longer.

I consider 10 devices as enough quantity. 

You can increase the number ``in range(10)``, but check th running time before use in production.

**Comment by idokaplan** [comment]
Thanks!
