### ISSUE TITLE
Bug with the logical disks discovery

### ISSUE THREAD

**Issue by idokaplan** [YSmetana/raid_arcconf_zabbix_lld#4]
Logical disk not must to be listed continuously (0,1,2...).

For example, Logical disk number 0 could be deleted, so the logical disk list starts with logical disk number 1, but #OBJ_ID value will be still 0 (but it should be number 1).

Is there a way to save "Logical device number" as a variable and not to use "ld_num"?

Please advise.
Thanks!
Ido

**Comment by idokaplan** [comment]
Yuriy?
:(

**Comment by YuriySm** [comment]
You are right. I missed that out. Would you be so kind to pull the changes or redownload the script and check again?

Tnx.

**Comment by idokaplan** [comment]
Thanks – much appreciated.
I'm not sure why, but #OBJ_ALIAS is missing in the last array - #OBJ_ID is 4
Do you know why?

python c:\temp\raid_arcconf_zabbix_lld.py ld -1 lld
{"data": [{"{#OBJ_ALIAS}": "RAID1", "{#OBJ_TYPE}": "ld", "{#OBJ_ID}": 0}, {"{#OBJ_ALIAS}": "RAID1", "{#OBJ_TYPE}": "ld", "{#OBJ_ID}": 1}, {"{#OBJ_ALIAS}":"RAID1","{#OBJ_TYPE}":"ld", "{#OBJ_ID}": 2}, {"{#OBJ_TYPE}": "ld", "{#OBJ_ID}": 4}]}

**Comment by idokaplan** [comment]
Yuriy?
:(
