### ISSUE TITLE
wrong syntaxis in conf file 

### ISSUE THREAD

**Issue by dvorobiev** [YSmetana/raid_arcconf_zabbix_lld#6]
In line
`UserParameter=raid.arcconf[*],/opt/zabbix_scripts/raid_arcconf_zabbix_lld/raid_arcconf_zabbix_lld.py "$1" "$2" "$3"`
need add "pyhon" before name of scrypt
Correctly write this:
`UserParameter=raid.arcconf[*],python /opt/zabbix_scripts/raid_arcconf_zabbix_lld/raid_arcconf_zabbix_lld.py "$1" "$2" "$3"`

**Comment by YuriySm** [comment]
Hello! There is shebang ``#!/usr/bin/env python`` in the script. It should run Python interpreter and execute the script as Python code. At least under the *nix OS.

Read more about shebang: https://en.wikipedia.org/wiki/Shebang_(Unix) .
